exports.run = (bot, message, args) => {
    const Discord = require('discord.js')
    const fs = require('fs')
    if (!message.member.hasPermission("BAN_MEMBERS")) return message.reply("у вас недостаточно прав!")
    let warnmember = message.mentions.users.first()
    let moder = message.author
    let warnreason = args.slice(1).join(' ')
    if (!warnmember) return message.reply("пожайлуста, укажите пользователя")
    if (!warnreason) return message.reply("пожайлуста, укажите причину бана")
    var banRole = message.guild.roles.find('name', 'BANNED')
    var dj = message.guild.roles.find('name', 'DJ 🎧')
    var piar = message.guild.roles.find('name', '💬┊Пиарщик')
    var helper = message.guild.roles.find('name', '❓┊Хелпер')
    var moder = message.guild.roles.find('name', '🔧┊Модератор')
    var mladm = message.guild.roles.find('name', '💎┊Мл. Админ')
    var admin = message.guild.roles.find('name', '👑┊Админ')
    var personal = message.guild.roles.find('name', '🔧┊Персонал Blancoo')
     let warnresult = new Discord.RichEmbed()
        .setColor('#ff0000')
        .setTitle('Вам был выдан бан!')
        .addField('От сервера Blancoo',`**Модератор:** ${moder}\n**Причина:** ${warnreason}`)
        .setThumbnail('http://pngimg.com/uploads/exclamation_mark/exclamation_mark_PNG29.png')
    var embed = new Discord.RichEmbed()
        .setColor('#ff0000')
        .setTitle('Выдан бан!')
        .addField('Подробнее...',`**Модератор:** ${moder}\n**Нарушитель:** ${warnmember}\n**Причина:** ${warnreason}`)
    message.guild.member(warnmember).removeRole(dj)
    message.guild.member(warnmember).removeRole(piar)
    message.guild.member(warnmember).removeRole(helper)
    message.guild.member(warnmember).removeRole(moder)
    message.guild.member(warnmember).removeRole(mladm)
    message.guild.member(warnmember).removeRole(admin)
    message.guild.member(warnmember).removeRole(personal)
    warnmember.send(warnresult)
    message.channel.send(embed)
    message.guild.member(warnmember).addRole(banRole)
}
exports.help = {
    name: 'ban'
}
